/**
 * The CLI arm's artifact: a real command-line tool, generated from the registry.
 *
 * Help text is commander's, not ours. That matters more than convenience. The `--help` output is a
 * *measured* quantity in this experiment, and while it was hand-rendered the README had to carry a
 * caveat that a terser wording would have handed this format a win by construction. Generated by the
 * most widely deployed CLI framework in the ecosystem, the caveat goes away — and the layout becomes
 * the one models have read the most, which is the fairest version of the familiarity confound rather
 * than an attempt to hide it.
 */

import { Command, Option } from "commander";
import type { Api } from "../api.ts";
import { applyFilter } from "../filter.ts";
import { byName, isArrayParam, type Operation, type Param, type Registry, renderPath } from "../spec.ts";

export const PROGRAM = "api";

function describe(operation: Operation): string {
  return [operation.summary, operation.description].filter(Boolean).join("\n\n");
}

function optionFor(param: Param): Option {
  const option = new Option(`--${param.name} <value>`, param.description || param.name);
  if (param.default !== undefined) option.default(param.default);
  if (param.enum.length > 0) option.choices([...param.enum]);
  if (isArrayParam(param)) option.argParser((value, previous: string[] = []) => [...previous, value]);
  return option;
}

/** Build the command tree. Execution is injected so the same tree can be printed without running. */
export function buildProgram(
  registry: Registry,
  execute?: (operation: Operation, args: Record<string, unknown>) => Promise<string>,
): Command {
  const program = new Command()
    .name(PROGRAM)
    .description(registry.title)
    .helpOption("-h, --help", "show help")
    .configureOutput({ writeOut: (s) => process.stdout.write(s) })
    .exitOverride();

  for (const operation of registry.operations) {
    const command = program.command(operation.name).description(describe(operation)).exitOverride();
    for (const param of operation.params) {
      if (param.location === "path") command.argument(`<${param.name}>`, param.description || param.name);
      else command.addOption(optionFor(param));
    }
    if (execute) {
      command.action(async (...received: unknown[]) => {
        const positional = operation.params.filter((p) => p.location === "path");
        const options = (received[positional.length] ?? {}) as Record<string, unknown>;
        const args: Record<string, unknown> = { ...options };
        positional.forEach((p, index) => {
          args[p.name] = received[index];
        });
        process.stdout.write(await execute(operation, args));
      });
    }
  }
  return program;
}

/** `api --help`, exactly as the installed binary prints it. */
export function rootHelp(registry: Registry): string {
  return buildProgram(registry).helpInformation();
}

/** `api <command> --help`, exactly as the installed binary prints it. */
export function commandHelp(registry: Registry, name: string): string {
  const program = buildProgram(registry);
  const command = program.commands.find((c) => c.name() === name);
  if (!command) throw new Error(`unknown command: '${name}'`);
  return command.helpInformation();
}

/** Root help plus every command's help — what a preloaded-manual arm would be handed up front. */
export function fullHelp(registry: Registry): string {
  return [rootHelp(registry), ...registry.operations.map((op) => commandHelp(registry, op.name))].join("\n");
}

/** Run one operation, serialising the response the same way every arm does. */
export async function invoke(
  api: Api,
  registry: Registry,
  name: string,
  args: Record<string, unknown>,
  filter?: string,
): Promise<string> {
  const operation = byName(registry, name);
  const pathValues: Record<string, unknown> = {};
  const query: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(args)) {
    if (value === undefined || value === null || value === "") continue;
    const param = operation.params.find((p) => p.name === key);
    if (param?.location === "path") pathValues[key] = value;
    else query[key] = value;
  }
  const response = await api.get(renderPath(operation, pathValues), query);
  const body = JSON.stringify(response.body);
  return filter ? await applyFilter(response.body, filter) : body;
}
